[postgres]
host = "ec2-99-81-177-233.eu-west-1.compute.amazonaws.com"
port = 5432
database = "d8rmlsdc9jeij5"
user = "vsxakhoegcbzbs"
password = "5c54ca0d2ec2c73e9e2a959b0f7cc30a6767bac22080124543c31f7d772baffe"


[gcp]
host = "34.77.215.47"
port = 5432
database = "postgres"
user = "postgres"
password = "Chocolate99!"


[local]
host = "localhost"
port = 5432
database = "ETF_backup"
user = "Veekking"
password = "Chocolate99!"

[do]
user = "doadmin"
password = "vvRlomgigHKwU8Gl"
host = "db-postgresql-lon1-etfs-do-user-8225426-0.b.db.ondigitalocean.com"
port = 25060
database = "defaultdb"
sslmode = "require"


[gcp_service_account]
type = "service_account"
project_id = "green-diagram-337510"
private_key_id = "1510bfffba580bbaeb281dc9877038ad9c7a1df8"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAqWjre2Upy8n1\nx4zn3G5B428bYFWAK5RSCOWX7tyFZYrVk3m5OzYz6ok0mec/tdPZbJSFIpM2+O9n\no67KvJUAkvtTt7jcHPNaB48NMskHMJGAaOXTQWrPv8iacEaU6/TG23SpGVRmHORn\ntLJK7bDomZ2+xMwHQU3o2i+cjQo2BGFnRIj68HFiAZzFPZXGyqmxCnesuqtlVzqR\nYmsX8r89dcNCBJuiPSnAY8X4EYJ72iuSy8GXl4stqJfreO7YMsVf4rbjzArDQ3nO\njDc4VEOY8fjvEEylDkzhiqUJtjDGTgHhrnFegBym9JEkxTuHMrEui/D+zYTdFa5f\nggNhprFvAgMBAAECggEAB7Laaf88wqNwhwSOPmvSE7jayDJz6aclm65QmrwWqz5P\na0tpneGHBcW0HD0rPufbyE8M5QBRVGF6th6tIjihp6AgsIX+ovxW/XPmPE08OCSC\n+QaJgflQC/rQMWaV4URHx9Fj42H0AbMg85UGccZrYiGDgeilo/fZn/baNRxz3+mM\nDk5lMZuHLJoIlHveYdZ1/DbUL4O8eT0hfKAz1xPEr8YgMddnbhHGQqb7uto5U1qR\n0F/NKjZy204xQq2aL1ZzoDLcTeMqiy7L8otRScry+G7CGpwjYlkLxRBCh60tHzJD\nZdsq8QWUm6vfiK1hQNApJIIFUHtXAW6phwFgagphEQKBgQDiWlyjEEYOitwnEe5X\n/ugL+739OhdhMR4rD71Aoq4QZpjryAjzx13VHWElRCjWd4VmYZFYqSSoeAph7kEW\nwa5BsvXf7O2z1/cMbBAN0E5V148D32ZXHxiP0claLhEkqIu1fm3M8+UU/EaFZxv7\nVXdWaaD+swJ7v/wElt8W/Go7+QKBgQDZ5WDFXUKueLjoi97tGaiRRZoS3bZ6OvZQ\nAOFT8M4xUIgML9hARz5sAvaOyRBVcrkzWUqlhRAzWFIBVIRavNUuycAnCmZlzAUA\nNF9eCmDWIfntBvLyRIU63DoVxBjREmrbarTdakdxJ3uDfTJDpm1uYQqnZyULywc6\nKdJ6zxaipwKBgQCKvIn1JF9cQH5JsDLfWo0N80Hy+O0llD6CdEYyXMPFp6zpL5VV\nHgiEPFqzxcAmG+H266xzpFCktdbfSXI5qYLOIAuWMZlMVv3EbmO0o82vzcyJuh73\nHUcnt5Trojq9tlTTbGeObJsnrqzmzVkYRr07iMi19DB8eyLUCUk5xIK0uQKBgFEX\nYopRCO3xk69HzrEiqW9XHd4DkVOv+dcQXMtmhPYpaFhQvgQ9/2cnOycsgN2sEmyf\nwH4VJVBWgD5qe89hE12US+S7pBwib4IB+7P93MgUYPTrbyLmiUa8iwlqr2mvlwEN\nlz4HvYrJDNiEkV5H49X+W36tjkXzSz9ELUbzJxNlAoGALVw8Q954MMbqYHPJ+NFp\nYokfay8gNGDjYDiD6U7nrxRnQ7Rt0H/eeN3NmP+mCLKjv3eo0J51rq9C9ftigy9e\nuPHzInpUHhoqOKc1crxjqeR6vuCOs6pHQFWToscH2sugmBp5ZhWERHRM2yotrvlH\n+gLC8HysYXeomEDgjM7NNmU=\n-----END PRIVATE KEY-----\n"
client_email = "service-acc-etfs@green-diagram-337510.iam.gserviceaccount.com"
client_id = "109846114127630030047"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc-etfs%40green-diagram-337510.iam.gserviceaccount.com"


