[postgres]
host = "ec2-99-81-177-233.eu-west-1.compute.amazonaws.com"
port = 5432
database = "d8rmlsdc9jeij5"
user = "vsxakhoegcbzbs"
password = "5c54ca0d2ec2c73e9e2a959b0f7cc30a6767bac22080124543c31f7d772baffe"


[gcp]
host = "34.77.215.47"
port = 5432
database = "postgres"
user = "postgres"
password = "Chocolate99!"


[local]
host = "localhost"
port = 5432
database = "ETF_backup"
user = "Veekking"
password = "Chocolate99!"

[do]
user = "doadmin"
password = "vvRlomgigHKwU8Gl"
host = "db-postgresql-lon1-etfs-do-user-8225426-0.b.db.ondigitalocean.com"
port = 25060
database = "defaultdb"
sslmode = "require"


